permalink: /:year/:month/:title/
exclude:  README.md
name: Nicholas Kraak
description: The Big Shift Film Website
url: http://thebigshift.github.io
email: thebigshiftfilm@gmail.com (The Big Shift Film)
title: The Big Shift
subtitle: The Noir that becomes a Western
